/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ef5;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose David
 */
public class pantallaEF5 extends javax.swing.JFrame {

    JFileChooser abrirarc;
    Archivo abrirarchivo=new Archivo();
    String archivo_Abierto;
    String P;
    
    public pantallaEF5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bcola = new javax.swing.JButton();
        bpila = new javax.swing.JButton();
        blistadoble = new javax.swing.JButton();
        blistacircular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        varchivo = new javax.swing.JLabel();
        ordenado = new javax.swing.JLabel();
        ord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargar.setText("cargar");
        cargar.setActionCommand("cargar ");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenar por");

        bcola.setText("cola");
        bcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcolaActionPerformed(evt);
            }
        });

        bpila.setText("pila");
        bpila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpilaActionPerformed(evt);
            }
        });

        blistadoble.setText("lista doble");
        blistadoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blistadobleActionPerformed(evt);
            }
        });

        blistacircular.setText("lista circular");
        blistacircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blistacircularActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivo de entrada");

        varchivo.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ordenado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(ord)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(varchivo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cargar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blistadoble)
                    .addComponent(bpila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcola)
                    .addComponent(blistacircular))
                .addGap(0, 224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(varchivo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordenado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bpila)
                                    .addComponent(bcola))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(blistadoble)
                                    .addComponent(blistacircular))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cargar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
       abrirarc =new JFileChooser();
       abrirarchivo.Leer(AbrirArchivo());
      varchivo.setText(abrirarchivo.getTexto());
    }//GEN-LAST:event_cargarActionPerformed

    private void bpilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpilaActionPerformed
         P="p";
        Ordenar(P);
    }//GEN-LAST:event_bpilaActionPerformed

    private void bcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcolaActionPerformed
        P="c";
        Ordenar(P);
    }//GEN-LAST:event_bcolaActionPerformed

    private void blistadobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blistadobleActionPerformed
        P="lc2";
        Ordenar(P);
    }//GEN-LAST:event_blistadobleActionPerformed

    private void blistacircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blistacircularActionPerformed
        P="lc";
        Ordenar(P);
    }//GEN-LAST:event_blistacircularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaEF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaEF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaEF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaEF5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaEF5().setVisible(true);
            }
        });
    }
    public void Ordenar(String orden){
    String [] vec;
    vec=abrirarchivo.getTexto().split(",");
    int n=0;
    switch(orden){
        case "p":
            System.out.println("Orden Pila");
        Pila pila = new Pila(0);
        for(int i=0;i<vec.length;i++){
            n=Integer.parseInt(vec[i]);
           
               pila.Apilar(n);
        }
        pila.Imprimir();
            System.out.println("");
       break;
        case"c":
             System.out.println("Orden Cola");
         Cola cola = new Cola(0);
           for(int i=0;i<vec.length;i++){
            n=Integer.parseInt(vec[i]);
          
               cola.Encolar(n);
            }
          cola.Imprimir();
            System.out.println("");
        break;
        case"lc":
             System.out.println("Lista Circular");
           ListaCircular listacircular = new ListaCircular(0);  
           for(int i=0;i<vec.length;i++){
            n=Integer.parseInt(vec[i]);
               
               listacircular.InsertarAlFinal(n);
            }
        
           listacircular.Imprimir();
            System.out.println("");
        break;
        case"lc2":
             System.out.println("Lista Doble");
           ListaDoble listadoble = new ListaDoble(0);  
           for(int i=0;i<vec.length;i++){
            n=Integer.parseInt(vec[i]);
         
               listadoble.InsertarAlFrente(n);
            }
           listadoble.Imprimir();
            System.out.println("");
        break;
    
    }
    
    
    
    }
   
    public String AbrirArchivo(){
     String nombrearchivo="";
        //Crean los filtros para el tipo de archivo que van a permitir que se abran, en este caso es solo es bbm
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(".txt","txt");
        
        //inicializan el dialogo para escoger textos
        abrirarc=new JFileChooser();  
        
        //Le agregan el filtro al dialogo de texto
        abrirarc.setFileFilter(filtro);
        
        //Es la variable entero que guarda el tipo de operacion que se hace, aceptar o cancelar
        int returnVal = abrirarc.showOpenDialog(this);
        
        //Verifica el tipo de accion que se realizó, si se dio click en "Aceptar" obtiene la ruta del doc seleccionado
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            nombrearchivo=abrirarc.getSelectedFile().getPath();
         //Guarda en una variable global el nombre del archivo que se encuentra abierto,
         //si se hacen cambios y le damos click en guardar, sobreescribe el archivo
          archivo_Abierto = nombrearchivo;
        }
    
    return nombrearchivo;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcola;
    private javax.swing.JButton blistacircular;
    private javax.swing.JButton blistadoble;
    private javax.swing.JButton bpila;
    private javax.swing.JButton cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ord;
    private javax.swing.JLabel ordenado;
    private javax.swing.JLabel varchivo;
    // End of variables declaration//GEN-END:variables
}
